### ISSUE TITLE
Networking issue when running docker-compose

### ISSUE THREAD

**Issue by FazleArefin** [UlisesGascon/sample-terraform-localstack#1]
When running `docker-compose up`, I encountered this error:

```
Creating network "sample-terraform-localstack_default" with the default driver
ERROR: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
```

I found a solution here https://stackoverflow.com/questions/43720339/docker-error-could-not-find-an-available-non-overlapping-ipv4-address-pool-am which required adding `network_mode: bridge` to the `docker-compose.yml` file.

**Comment by UlisesGascon** [comment]
Thanks @fazlearefin !! :)
